import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en' data-theme='night'>
			<body className='flex justify-center flex-col items-center'>
				<nav className='w-[760px] mx-auto mt-[5%] text-center'>
					{' '}
					<ul className='menu menu-horizontal gap-16 bg-base-200 rounded-box'>
						<li>
							<Link href='/'>Home</Link>
						</li>
						<li>
							<Link href='/input-krs'>Input</Link>
						</li>
						<li>
							<Link href='/edit-krs'>Edit</Link>
						</li>
					</ul>
				</nav>
				<main className='w-[760px] mx-auto mt-8'>{children}</main>
			</body>
		</html>
	);
}
